# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20161031_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='support_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
