# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20161101_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('standby_phone', models.CharField(max_length=20)),
                ('teamleader', models.CharField(max_length=50)),
                ('sdo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='configuration_owner',
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='service_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Service_status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='operational_support_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operational_support', to='inventory.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='standby_support_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='standby_support', to='inventory.Team'),
            preserve_default=False,
        ),
    ]
