# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160803171240 on 2016-11-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20161101_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration_owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='configuration_owner',
            name='sdo',
        ),
        migrations.RemoveField(
            model_name='configuration_owner',
            name='teamleader',
        ),
        migrations.AlterField(
            model_name='configuration_owner',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Team'),
        ),
    ]
